### ISSUE TITLE
Isn't this just a straight decompiled version of Karlin-Z's ChopBamboo plugin?

### ISSUE THREAD

**Issue by akira0245** [carvelli/Slice-Is-Right#1]

**Comment by akira0245** [comment]
https://github.com/Karlin-Z/DalamudPlugins/tree/main/plugins/ChopBamboo

**Comment by DiggityMan420** [comment]
yes but even so those are The slice is right he has ( an has stated he can only do CN) now he should give props where props are due but u dont know maybe he has rights to publish this  either way this worked for US client and the other i cant get too so if u can update great

**Comment by carvelli** [comment]
Added to the README in 4e33fa1
