### ISSUE TITLE
Custom Repo URL?

### ISSUE THREAD

**Issue by trini0n** [carvelli/Slice-Is-Right#3]
Hey there, wanted to try this plugin out but couldn't find a custom repo URL to add to Dalamud in game?  Or is there a different method of installing the plugin?

**Comment by CrispyJakal** [comment]
I am also looing for a custom repo URL, haven't found any other way to put this Plugin onto XIV Launcher

**Comment by carvelli** [comment]
Hi, please see my other repo for the URL:

https://github.com/carvelli/Dalamud-Plugins
