### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by zenrar** [carvelli/Slice-Is-Right#4]
https://i.imgur.com/Yr9vLTi.jpeg

didn't work at all. v 4.0.0.0 via dalamudRepoBrowser.

**Comment by carvelli** [comment]
I've tested it just now and it seems to work just fine.

There's a limit to how far you can be away for things to still be visible. Are you actually on the platform? The screenshot is a pretty unusual camera angle, and I have no idea where you are in it (or if you're using some freecam mod etc.).
