### ISSUE TITLE
Crashes upon closing game

### ISSUE THREAD

**Issue by helioboros** [carvelli/Slice-Is-Right#5]
As of yesterday, the Slice is Right plugin seems to crash FFXIV whenever trying to exit the game while signed on as a character. (Logging off and then exiting the game closes it with no crash.)

Tested multiple times with other plugins, and disabling only this one cleared up the issue.

Have no clue what could have updated ingame for this to suddenly be happening but it's worth knowing either way.

![image](https://user-images.githubusercontent.com/37154824/181816072-92aa17dc-ca9d-41e2-a0f2-f0fe80e43cc2.png)

**Comment by carvelli** [comment]
Hi,

When exactly does this happen? Is this only when logging out in the Gold
Saucer + the slice is right gate is currently running? Just exitting the
game normally, even in the Gold Saucer, doesn't crash it for me.

Am Fr., 29. Juli 2022 um 19:49 Uhr schrieb Soren ***@***.***>:
