### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by sauronshotdogs** [carvelli/Slice-Is-Right#7]
Loving the plugin. Would it be possible to make a similar one for Any Way the WInd Blows?

**Comment by carvelli** [comment]
I think I looked into it a few months back, but Any Way The Wind Blows only spawns Ultros AFTER you can no longer move, so there's no benefit having that.

**Comment by sauronshotdogs** [comment]
Ah, that sucks. Thanks for replying so quickly though!
