### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Gingerfloof** [carvelli/Slice-Is-Right#9]
How do I put this into my game? Much of this process is confusing to me..

**Comment by carvelli** [comment]
Under Dalamud Settings > Experimental > Custom Plugin Repositories, add

```
https://raw.githubusercontent.com/carvelli/Dalamud-Plugins/master/dist/pluginmaster.json
```

**Comment by Gingerfloof** [comment]
Apologies for it being something so simple! Thank you <3
